### ISSUE TITLE
arc-shaped tablet area

### ISSUE THREAD

**Issue by abbytec** [Kuuuube/Circular_Area#1]
Hi! I think it could be a nice idea to do this. Specially for people who uses tablet putting his wrist on a fixed place and moves his hand like a curve.

**Comment by abbytec** [comment]
Sorry about my description, i was actually referring to something more like this 
https://imgur.com/0BjkhlS

**Comment by Kuuuube** [comment]
Requests for more shapes are unlikely to go through. Finding or deriving formulas that nicely map anything besides circles and squares is not easy. 

However, I am open to suggestions if you find explicit mappings which use unit coordinates and (x,y) inputs.
